#!/usr/bin/env python3
"""Fold a fresh builder export into the site without losing hand-written work.

Background
----------
`index.html` is generated by a visual builder. Twice in this repository's
history (8d450d7, then 6e00315) a new export was committed straight over the
old one, and each time it silently deleted every customization that had been
added since -- including the entire Supabase integration.

This script exists so that never happens again. It treats the export as one
side of a three-way merge rather than as a replacement:

    baseline   the raw export the current customizations were built on
    ours       the live site, customizations included
    theirs     the new export you just downloaded

Usage
-----
    python3 tools/apply.py path/to/new-export.html

On success it rewrites index.html and Etihad_ERP.html, refreshes the stored
baseline, and prints which customizations it verified. On conflict it writes
the conflicted inner document to tools/.conflict.html and stops without
touching the site, so nothing is half-applied.
"""

import os
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import bundle  # noqa: E402
import checks  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOOLS = os.path.join(ROOT, "tools")
BASELINE = os.path.join(TOOLS, "baseline", "export.html")
TARGETS = ("index.html", "Etihad_ERP.html")
CONFLICT = os.path.join(TOOLS, ".conflict.html")


def merge(base, ours, theirs):
    """Three-way merge of three inner documents. Returns (text, conflicted)."""
    tmp = tempfile.mkdtemp()
    paths = {}
    for name, text in (("base", base), ("ours", ours), ("theirs", theirs)):
        paths[name] = os.path.join(tmp, name)
        with open(paths[name], "w", encoding="utf-8") as fh:
            fh.write(text)
    result = subprocess.run(
        ["git", "merge-file", "-L", "current site", "-L", "previous export",
         "-L", "new export", paths["ours"], paths["base"], paths["theirs"]],
        capture_output=True,
    )
    with open(paths["ours"], encoding="utf-8") as fh:
        return fh.read(), result.returncode != 0


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    new_export = argv[1]
    for path in (new_export, BASELINE, os.path.join(ROOT, "index.html")):
        if not os.path.exists(path):
            print("missing: %s" % path)
            return 1

    base = bundle.get_template(bundle.read(BASELINE))
    ours = bundle.get_template(bundle.read(os.path.join(ROOT, "index.html")))
    theirs_text = bundle.read(new_export)
    theirs = bundle.get_template(theirs_text)

    merged, conflicted = merge(base, ours, theirs)
    if conflicted:
        bundle.write(CONFLICT, merged)
        print("MERGE CONFLICT -- nothing was written to the site.")
        print("Resolve the markers in %s, then re-run with that file." % CONFLICT)
        print("\nThe usual conflict is the bundled asset id in <head>:")
        print("keep the NEW export's id and re-add the customizations below it.")
        return 1

    # The new export supplies the loader and asset manifest; only the inner
    # application document carries merged content.
    rebuilt = bundle.set_template(theirs_text, merged)

    inner = bundle.verify(rebuilt)
    report = checks.run(inner)
    if report.failed:
        print("Merge succeeded but these customizations went missing:")
        for name, why in report.failed:
            print("  MISSING  %s -- %s" % (name, why))
        print("\nRefusing to write. Inspect %s" % CONFLICT)
        bundle.write(CONFLICT, merged)
        return 1

    for target in TARGETS:
        bundle.write(os.path.join(ROOT, target), rebuilt)
    bundle.write(BASELINE, theirs_text)

    print("Applied new export and kept %d customizations:" % len(report.passed))
    for name in report.passed:
        print("  ok  %s" % name)
    print("\nWrote %s and refreshed the baseline." % ", ".join(TARGETS))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
